# Generated by Django 4.1.5 on 2023-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_premise_vehicletype_booking_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
