# Generated by Django 4.1.5 on 2023-02-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_end_time_alter_booking_start_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
